spring.application.name=inventory-tracker
spring.datasource.url=jdbc:postgresql://dpg-d6j2kn5m5p6s73df1vhg-a:5432/inventoryaztradingcc_dgzv?sslmode=require
spring.datasource.username=azjoeschmo
spring.datasource.password=uME7vuDACoEcrW2p1HFpNj0sTn5QCguH

# --- User Login Credentials ---
spring.security.user.name=2
spring.security.user.password=1
